name: C CI

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get compiler version
      run: make version
    - name: make project
      run: make
    - name: run tests
      run: make test
    - name: groundstation
      run: cd groundstation && make
